# Generated by Django 5.2.10 on 2026-01-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='duration',
            field=models.PositiveSmallIntegerField(choices=[(60, '1 Hour'), (120, '2 Hours'), (240, '4 Hours'), (480, '8 Hours'), (1440, '1 Day'), (4320, '3 Days')], db_index=True, default=None),
            preserve_default=False,
        ),
    ]
